Add option to hide author, date, comment block
Voog/design-amsterdam pull request #149
Opened 2018-11-06 13:16 UTC by siimha

1. Add option to hide author, date and comment block.
2. Use global, blog & article scope for given settings.
Close #213 

Testimine:
* [ ] Kasuta testimisel CMS haru 2936-settings-editor-toggle, mis on seotud lahendusega https://github.com/Edicy/edicy_cms/pull/2941
* [ ] Kontrollida, kas objekti tüübiks on toggle ja kas kuvatakse tooltipi (tõlkeid ei ole pealkirja, nupu nime ja tooltipi puhul kuvatud, kuna need peavad enne minema tõlkimisse).
```
menuItems: [
        {
          "titleI18n": "comments",
          "type": "toggle",
          "key": "show_comments",
          "tooltipI18n": "toggle_current_article_comments",
          "states": {
            "on": true,
            "off": false
          },
        }
      ],
```

* [ ] Kontrollida, kas tulemus vastab [disainile](https://www.figma.com/file/PXwsuAGp6Fgnlc4MEf3nKQ6V/voog-hide-blog-elements) ja kas nupule vajutades muutub väärtus
* [ ] Kontrollida, kas esmasel kasutamisel on kommentaarid, kuupäev ja autor kuvatud (võimalik, et mõnel mallil puuduvadki kommentaarid, autor või kuupäev). 
* [ ] Kontrollida, kas toggle olek on esmasel kasutamisel enabled, kui väärtusi pole määratud
<img width="330" alt="screen shot 2018-10-19 at 09 31 12" src="https://user-images.githubusercontent.com/35253483/47201231-d2762480-d381-11e8-9f8d-559d8b621d92.png">

* [ ] Kontrollida, kas väärtuse muutusel peidetakse/kuvatakse kommentaarid, kuupäev ja autor 
* [ ] Kontrollida, kas blogilistingu vaates tehtud muudatused kehtivad ka artikli vaates, kui artikli vaates pole salvestatud väärtusi ja kas artikli vaates tehtud muudatused kirjutavad üle blogilistingu vaate väärtused 
* [ ] Kontrollida ka teisi objekti tüüpe, lisades sinna tooltipi ja jägides, et antud objekt toimiks korrektselt ja stiil oleks korras.

2020-06-02 14:56 UTC, entertthk commented on components/blog-settings-editor.tpl
> +          "tooltipI18n": "toggle_current_article_comments",
vale: "tooltipI18n": "toggle_current_article_comments",
õige: "tooltipI18n": "toggle_all_articles_comments",

2020-08-11 07:30 UTC, siimha commented
- [ ] Listingu vaates ei toimi kuupäeva peitmise eelvaade. Kasutatakse editoris vale klassi `$('.article-date.site-data')` peaks olema `$('.post-date.site-data')`

2020-08-11 07:52 UTC, siimha commented on layouts/blog___news.tpl
> +            <div class="add-settingsBtn-container">{% include "blog-settings-editor" %}</div>
Seda konteinerit ei ole vaja `<div class="add-settingsBtn-container">`. Includitud editoris on nupu konteiner juba olemas `<div class="blog-settings-wrap">` ja paddingu võib lisada selele:
```
.blog-settings-wrap {
  padding-bottom: 30px;
}
```

2020-08-11 07:55 UTC, siimha commented on layouts/blog___news.tpl
> +            <div class="add-settingsBtn-container">{% include "blog-settings-editor" %}</div>
Kuna me ei kasuta antud mallis klasside nimetamise puhul cameCase stiili `add-settingsBtn-container`, siis tuleks ka seda vältida, aga see lihtsalt märkuseks, kuna seda klassi polegi vaja.

2020-08-11 08:11 UTC, siimha commented on components/blog-settings-editor.tpl
> +      show_comments = Boolean(globalDataValues.show_comments)
Hea tava on panna muutuja lõppu [semikoolon](https://news.codecademy.com/your-guide-to-semicolons-in-javascript/).

2020-08-11 08:11 UTC, siimha commented on components/blog-settings-editor.tpl
> +        },
Objektide lõpus üleliigsed komad

2020-08-11 08:11 UTC, siimha commented on components/blog-settings-editor.tpl
> +       var $articleDate = $('.post-date.site-data');
Siin on joondus läinud paigast

2020-08-11 08:11 UTC, siimha commented on components/blog-settings-editor.tpl
> +        );
Siin on funktsiooni lõpus olev sulg läinud uuele reale ja lõpus on üleliigne koma.

2020-08-11 08:11 UTC, siimha commented on components/article-settings-editor.tpl
> +<div class="article-settings-wrap">
Selle võiks joondada paremale

2020-08-11 08:12 UTC, siimha commented on components/blog-settings-editor.tpl
> +<div class="blog-settings-wrap">
Selle võiks joondada paremale

2020-08-11 08:15 UTC, siimha commented on components/article-settings-editor.tpl
> +      },
Joondus paigast ja üleliigsed komad objektide lõpus

2020-08-11 08:53 UTC, siimha commented on components/blog-settings-editor.tpl
> +      type: 'site',
Koma üleliigne, kui objektis on üks väätus

2020-08-11 14:00 UTC, tanelj commented on components/comments-article.tpl
> +  <aside class="comments cfx{% if show_article_comments == false %} hide-article-comments{% endif %}">
Kommentaaride HTML'i ei tohiks välja renderdada avalikus vaates kui show_article_comments == false.

Kood peaks olema pigem:
```
{% if editmode or show_article_comments != false %}
 <aside class="comments cfx{% if show_article_comments == false %} hide-article-comments{% endif %}">

```

2020-08-28 09:44 UTC, tanelj requested changes
It's working correctly, but there is one bug (wrong endif location).

2020-08-28 09:44 UTC, tanelj commented on components/comments-article.tpl
> +  {% endif %}
`{% endif %}` is in wrong location. It should be just after current `</aside>` block.

```
  </aside>
{% endif %}
```

At the moment the HTML is broken and comments are shown in public view.

2020-08-30 20:31 UTC, tanelj approved these changes

2020-08-31 19:21 UTC, merged